name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: pai-website-novo-setembro/dental-website/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: pai-website-novo-setembro/dental-website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pai-website-novo-setembro/dental-website/package-lock.json') }}-${{ hashFiles('pai-website-novo-setembro/dental-website/**/*.[jt]s', 'pai-website-novo-setembro/dental-website/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pai-website-novo-setembro/dental-website/package-lock.json') }}-

      - name: Install dependencies
        working-directory: pai-website-novo-setembro/dental-website
        run: npm ci

      - name: Build with Next.js
        working-directory: pai-website-novo-setembro/dental-website
        run: npx next build && npx next export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pai-website-novo-setembro/dental-website/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
